services:
  postgres:
    image: pgvector/pgvector:pg16
    restart: always
    env_file: .env
    environment:
      POSTGRES_DB: ${POSTGRES_DATABASE}
      POSTGRES_USER: ${POSTGRES_USERNAME}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - '127.0.0.1:5433:5432'
    healthcheck:
      test:
        [
          'CMD-SHELL',
          'pg_isready -h 127.0.0.1 -p 5432 -U $${POSTGRES_USERNAME:-postgres} -d $${POSTGRES_DB:-postgres} || exit 1',
        ]
      interval: 5s
      timeout: 5s
      retries: 20

  redis:
    image: redis:alpine
    restart: always
    env_file: .env
    command:
      [
        'sh',
        '-c',
        'redis-server --appendonly yes --requirepass "$REDIS_PASSWORD"',
      ]
    volumes:
      - redis_data:/data
    ports:
      - '127.0.0.1:6380:6379'
    healthcheck:
      test: ['CMD', 'redis-cli', '-a', '${REDIS_PASSWORD}', 'PING']
      interval: 5s
      timeout: 5s
      retries: 20

  base: &base
    build:
      context: .
      dockerfile: Dockerfile
      target: development
    env_file: .env
    volumes:
      - storage_data:/app/storage
      - ./public:/app/public

  rails:
    <<: *base
    restart: always
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    entrypoint: docker/entrypoints/rails.sh
    command: ['bundle', 'exec', 'rails', 's', '-p', '3000', '-b', '0.0.0.0']
    ports:
      - '3000:3000'

  sidekiq:
    <<: *base
    restart: always
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    command: ['bundle', 'exec', 'sidekiq', '-C', 'config/sidekiq.yml']

volumes:
  postgres_data:
  redis_data:
  storage_data:
