export const STARCHATS_SET_USER = 'STARCHATS_SET_USER';
export const STARCHATS_RESET = 'STARCHATS_RESET';

export const ANALYTICS_IDENTITY = 'ANALYTICS_IDENTITY';
export const ANALYTICS_RESET = 'ANALYTICS_RESET';
